
%% Which cell count method to use for reporting

GateXY_Method_Report = 4; % Do not change


%% Patient ID & VesselID

expr_PatientID = 'P\d+';
[StartIdx_PatientID,EndIdx_PatientID] = regexp(SampleIDString,expr_PatientID);
if ~isempty(StartIdx_PatientID)
    PatientIDString = convertCharsToStrings(SampleIDString(StartIdx_PatientID+1:EndIdx_PatientID));
else
    PatientIDString = "";
end

expr_VesselID = 'V\d+';
expr_AppendSampleIDStr = '_[a-z]$'; 
[StartIdx_VesselID,EndIdx_VesselID] = regexp(SampleIDString,expr_VesselID);
if ~isempty(StartIdx_VesselID)
    VesselIDString = convertCharsToStrings(SampleIDString(StartIdx_VesselID+1:EndIdx_VesselID)); 
    [StartIdx_AppendSampleIDStr,EndIdx_AppendSampleIDStr] = regexp(SampleIDString,expr_AppendSampleIDStr);
    if ~isempty(StartIdx_AppendSampleIDStr)
        VesselIDString = strcat(VesselIDString,convertCharsToStrings(SampleIDString(StartIdx_AppendSampleIDStr+1:EndIdx_AppendSampleIDStr)));
    end
else
    VesselIDString = "";
end

clearvars StartIdx* EndIdx* expr_*;


%% Prepare SUMMARY Data for each SampleID

r_VidProp_Cell = {...
    convertCharsToStrings(SampleIDString),... 
    strcat(PatientIDString,VesselIDString),... 
    PatientIDString,... 
    VesselIDString,...  
    string(datetime('now'),'yyyyMMdd'),... 
    XY_PxLength,...
    Z_PxLength,...
    size(ImgStack_Crop,3),... 
    1/Z_PxLength,... 
    size(ImgStack_Crop,3)/(1/Z_PxLength)}; 

r_VidProp_Label_Cell = {...
    "SampleID",...
    "GroupID",...
    "PatientID",...
    "VesselID",...
    "AnalysisDate",...
    "XYPxLength_umpx",...
    "ZPxLength_sfr",...
    "NumFrame",...
    "FPS",...
    "VidLength_s"};

clearvars PatientIDString VesselIDString;

%%

r_Vol_Cell = {...
    oVolume.V.tMidPtSum_AllSkOBwMean_nL(:,:,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx),... 
    oVolume.V.tMidPtSum_AllSkOBwStdEr_nL(:,:,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx),... 
    oVolume.V.tMidPtSum_1SkOBwMean_SkMean_nL(:,:,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx),... 
    oVolume.V.tMidPtSum_1SkOBwMean_SkStdEr_nL(:,:,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx)};

r_Vol_Label_Cell = {...
    "Vol_OB_nL",... 
    "Vol_OB_Er_nL",...
    "Vol_SK_nL",... 
    "Vol_SK_Er_nL"};


%%

r_XYWinCellCt_Cell = oCellCt.Report_mCell{1,GateXY_Method_Report};

r_XYWinCellCt_Label_Cell = {...
    "Ct_Method",... 
    "Ct_CtMethod",...
    "Ct_Ct",... 
    "Ct_Conc_OB_KuL",... 
    "Ct_ZScr_Mean",...
    "Ct_ZScr_Stdev",... 
    "Ct_ZScr_25pct",...  
    "Ct_ZScr_50pct",... 
    "Ct_ZScr_75pct",... 
    "Ct_ZScr_BrightRankVal",...
    "Ct_Diameter_um",... 
    "Ct_Length_um",... 
    "Ct_WBCAreaFrac"};


%%

r_Ref_Man_CellCt_Cell = {...
    oCellConc_mCell{1,GateXY_Method_Report}.Ref_KuL,... 
    oCellCt.tFr_Manual_NR_Ct,... 
    oCellConc_mCell{1,GateXY_Method_Report}.Man_KuL.NR_AllSkOBwMean,... 
    oCellCt.tFr_Manual_R_Ct,... 
    oCellConc_mCell{1,GateXY_Method_Report}.Man_KuL.R_AllSkOBwMean}; 

r_Ref_Man_CellCt_Label_Cell = {...
    "Ref_Conc_KuL",...
    "Man_Ct_NR",...
    "Man_Conc_NR_OB_KuL",...
    "Man_Ct_R",...
    "Man_Conc_R_OB_KuL"};


%%

r_Velocity_Cell = {...
    oVelocity.tMidPtwMean_AllSkOBwMean_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength./Z_PxLength,... 
    oVelocity.tMidPtwMean_AllSkOBwStdEr_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength./Z_PxLength,... 
    oVelocity.tMidPtwMean_1SkOBwMean_SkMean_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength./Z_PxLength,... 
    oVelocity.tMidPtwMean_1SkOBwMean_SkStdEr_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength./Z_PxLength};

r_Velocity_Label_Cell = {...
    "Vcty_OB_ums",... 
    "Vcty_OB_Er_ums",...
    "Vcty_SK_ums",... 
    "Vcty_SK_Er_ums"};


%% 

r_SzSCS_Cell = {...
    oRadius.L.tMidPtMax_SkPxMean_AllSk_Diameter_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength,... 
    oRadius.L.tMidPtMax_SkPxMin_AllSk_Diameter_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength,... 
    oRadius.L.tMidPtMax_SkPxMax_AllSk_Diameter_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}.*XY_PxLength,...
    oSCS.SkelBlockLength,... 
    oSCS.SkelBlockLength.*XY_PxLength}; 

r_SzSCS_Label_Cell = {...
    "Diameter_Mean_um",... 
    "Diameter_Min_um",...  
    "Diameter_Max_um",...  
    "SkelBlockLength_px",...
    "SkelBlockLength_um"};


%%

r_Flag_Radius_Cell = {...
oFlag_Radius.L.tMidPt_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},... 
oFlag_Radius.L.tFr_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}};

r_Flag_Radius_Label_Cell = {...
    "FgRadius_tMdPct",... 
    "FgRadius_tFrPct"};

r_Flag_VctyEr_OB_Cell = {...
oFlag_VctyEr.OB.tMidPtwMean_1BlkAllSk_Metric_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},... 
oFlag_VctyEr.OB.tMidPtwMedian_1BlkAllSk_Metric_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},... 
oFlag_VctyEr.OB.tMidPt_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},...
oFlag_VctyEr.OB.tFr_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}};

r_Flag_VctyEr_OB_Label_Cell = {...
    "FgVctyEr_OB_tMdwMeanMetric",...
    "FgVctyEr_OB_tMdwMedianMetric",...
    "FgVctyEr_OB_tMdPct",...
    "FgVctyEr_OB_tFrPct"};

r_Flag_VctyEr_SK_Cell = {...
oFlag_VctyEr.SK.tMidPtwMean_1BlkAllSk_Metric_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},... 
oFlag_VctyEr.SK.tMidPtwMedian_1BlkAllSk_Metric_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},... 
oFlag_VctyEr.SK.tMidPt_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},...
oFlag_VctyEr.SK.tFr_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}};

r_Flag_VctyEr_SK_Label_Cell = {...
    "FgVctyEr_SK_tMdwMeanMetric",...
    "FgVctyEr_SK_tMdwMedianMetric",...
    "FgVctyEr_SK_tMdPct",...
    "FgVctyEr_SK_tFrPct"};

r_Flag_FlowStb_Cell = {...
oFlag_FlowStb.tMidPt_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},...
oFlag_FlowStb.tFr_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}};

r_Flag_FlowStb_Label_Cell = {...
    "FlagFlowStb_tMdFlagPct",...
    "FlagFlowStb_tFrFlagPct"};

r_Flag_RBCBkgd_Cell = {... 
oFlag_RBCBkgd_mCell{1,GateXY_Method_Report}.tMidPt_1BlkAllSk_Flag_Pct{1,1,1},...
oFlag_RBCBkgd_mCell{1,GateXY_Method_Report}.tFr_1BlkAllSk_Flag_Pct{1,1,1}}; 

r_Flag_RBCBkgd_Label_Cell = {...
    "FgRBCBkgd_tMdPct",...
    "FgRBCBkgd_tFrPct"};

r_Flag_CellCt_Cell = {...
 oFlag_CellCt_mCell{1,GateXY_Method_Report}.tMidPtwMean_1BlkAllSk_Metric_Cell{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},...
 oFlag_CellCt_mCell{1,GateXY_Method_Report}.tMidPt_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx},...
 oFlag_CellCt_mCell{1,GateXY_Method_Report}.tFr_1BlkAllSk_Flag_Pct{1,1,oCellConc_mCell{1,GateXY_Method_Report}.BlkSCS_BrightBlkorWinIdx}};

r_Flag_CellCt_Label_Cell = {...
    "FgCellCt_tMdwMeanMetric",... 
    "FgCellCt_tMdPct",...
    "FgCellCt_tFrPct"};


%% Combine all cells for output

r_Data_Cell = horzcat(r_VidProp_Cell,...
    r_Vol_Cell,...
    r_XYWinCellCt_Cell,...
    r_Ref_Man_CellCt_Cell,...
    r_Velocity_Cell,...
    r_SzSCS_Cell,...
    r_Flag_Radius_Cell,...
    r_Flag_VctyEr_OB_Cell,...
    r_Flag_VctyEr_SK_Cell,...
    r_Flag_FlowStb_Cell,...
    r_Flag_RBCBkgd_Cell,...
    r_Flag_CellCt_Cell);
    
r_Data_Label_Cell = horzcat(r_VidProp_Label_Cell,...
    r_Vol_Label_Cell,...
    r_XYWinCellCt_Label_Cell,...
    r_Ref_Man_CellCt_Label_Cell,...
    r_Velocity_Label_Cell,...
    r_SzSCS_Label_Cell,...
    r_Flag_Radius_Label_Cell,...
    r_Flag_VctyEr_OB_Label_Cell,...
    r_Flag_VctyEr_SK_Label_Cell,...
    r_Flag_FlowStb_Label_Cell,...
    r_Flag_RBCBkgd_Label_Cell,...
    r_Flag_CellCt_Label_Cell);


%%

% Save
writecell(r_Data_Cell,strcat(SaveFilePath,SampleIDString,'_ReportData_',timestamp,'.csv'));
writecell(r_Data_Label_Cell,strcat(SaveFilePath,SampleIDString,'_ReportLabel_',timestamp,'.csv'));
writecell(vertcat(r_Data_Label_Cell,r_Data_Cell),strcat(SaveFilePath,SampleIDString,'_ReportDataLabel_',timestamp,'.csv'));

clearvars r_* -except r_Data_Cell r_Data_Label_Cell;


%% Save list of variables in Workspace after previous module, if does not exist

% = OPTION 2: Save only new variables introduced in MODR
if ~exist('varList_MODR') && ~exist('varList_MOD07') 
    varList_MODR = who;
    varList_MODR = varList_MODR(~ismember(varList_MODR,varList_All));
    varList_All = vertcat(varList_All,varList_MODR);
    save(strcat(SaveMODFilePath,'Workspace_MODRVar_',SampleIDString,'_',timestamp,'.mat'),varList_MODR{:}); 
end


%% Save script in directory
% html format; do not evaulate code or save figures

ScriptName=mfilename;
PublishOptions=struct('format','html','showCode',true,'evalCode',false,'catchError',false,'figureSnapMethod','print','createThumbnail',false,'outputDir',SaveMODFilePath);
publish(strcat(ScriptName,'.m'),PublishOptions);

